DELETE FROM public.trade_locations WHERE created_by IS NULL;

INSERT INTO public.trade_locations (nome, cidade, estado, horario, descricao, tipo, ativo) VALUES
('Tchê Café', 'São Paulo', 'SP', 'Domingo 13h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Benfica / Banca Reboot', 'Fortaleza', 'CE', '09h–17h30', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Center Norte', 'São Paulo', 'SP', '14h–21h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Mercado Público', 'Porto Alegre', 'RS', '10h–18h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Campo Grande', 'Campo Grande', 'MS', '14h–20h', 'Importado / pendente de validação', 'ponto_fixo', true),
('MASP / Av. Paulista', 'São Paulo', 'SP', 'Domingo 10h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Praça Benedito Calixto', 'São Paulo', 'SP', 'Sábado 09h', 'Importado / pendente de validação', 'ponto_fixo', true),
('BarraShoppingSul', 'Porto Alegre', 'RS', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Praça da Espanha', 'Curitiba', 'PR', 'Sábado 10h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Praça Portugal', 'Fortaleza', 'CE', 'Sábado 10h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Praça da Liberdade / Coreto', 'Belo Horizonte', 'MG', 'Domingo 09h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Center Norte', 'São Paulo', 'SP', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Praça da República', 'São Paulo', 'SP', 'Domingo 08h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Parque Ibirapuera / Portão 3', 'São Paulo', 'SP', 'Sábado 09h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Bancas do Centro / Praça da Bandeira', 'Teresina', 'PI', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Bancas da Praia do Canto', 'Vitória', 'ES', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Praça dos Namorados', 'Vitória', 'ES', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Vila Velha', 'Vila Velha', 'ES', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Mestre Álvaro', 'Serra', 'ES', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Vitória', 'Vitória', 'ES', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Parque Potycabana', 'Teresina', 'PI', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Rio Poty', 'Teresina', 'PI', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Riverside Shopping', 'Teresina', 'PI', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Teresina Shopping', 'Teresina', 'PI', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Praça Deodoro', 'São Luís', 'MA', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Rua Grande / Centro Histórico', 'São Luís', 'MA', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Tacacá da Gisela', 'Manaus', 'AM', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Porto Velho Shopping / Estação Copa', 'Porto Velho', 'RO', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Praça dos Girassóis', 'Palmas', 'TO', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Palmas Shopping', 'Palmas', 'TO', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Extra Ponta Negra', 'Natal', 'RN', 'Domingo 15h', 'Importado / pendente de validação', 'ponto_fixo', true),
('JR Figurinhas', 'Natal', 'RN', 'Sábado 09h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Bancas de jornal no Centro', 'Manaus', 'AM', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Praça do Ferreira', 'Fortaleza', 'CE', '10h–12h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Parque do Cocó', 'Fortaleza', 'CE', 'Sábado 09h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping RioMar Fortaleza', 'Fortaleza', 'CE', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping RioMar Kennedy', 'Fortaleza', 'CE', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Iguatemi Bosque', 'Fortaleza', 'CE', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('North Shopping Fortaleza', 'Fortaleza', 'CE', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Del Paseo', 'Fortaleza', 'CE', 'Sexta 14h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Aldeota', 'Fortaleza', 'CE', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Parangaba', 'Fortaleza', 'CE', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Flamboyant Shopping', 'Goiânia', 'GO', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Goiânia Shopping', 'Goiânia', 'GO', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Bancas de jornal no Centro', 'Goiânia', 'GO', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Mangabeira Shopping', 'João Pessoa', 'PB', 'Sexta 12h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Banca Brasil / Made in Brazil Bar', 'Macapá', 'AP', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Maceió Shopping', 'Maceió', 'AL', 'Sábado 14h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Manauara Shopping', 'Manaus', 'AM', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Ponta Negra', 'Manaus', 'AM', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Studio 5 Shopping', 'Manaus', 'AM', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Praça XV', 'Rio de Janeiro', 'RJ', 'Sábado 08h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Praça da República', 'São Paulo', 'SP', 'Sábado 09h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Parque Ibirapuera', 'São Paulo', 'SP', 'Sábado 08h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Praça Portugal', 'Fortaleza', 'CE', '10h–12h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Banca da Praça Popular', 'Cuiabá', 'MT', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Praça Nova / Zona Oeste', 'Campo Grande', 'MS', 'Sábado 16h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Banca Elite', 'Campo Grande', 'MS', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Banca Modular', 'Campo Grande', 'MS', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Norte Sul Plaza', 'Campo Grande', 'MS', 'Sábado 10h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Bosque dos Ipês', 'Campo Grande', 'MS', 'Sábado 14h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Panini Point Brasília', 'Brasília', 'DF', 'Sábado 14h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Banca do Brito / 106 Norte', 'Brasília', 'DF', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Roraima Garden Shopping', 'Boa Vista', 'RR', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Pátio Roraima', 'Boa Vista', 'RR', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Evento de troca agendado', 'Belém', 'PA', 'Sábado 13h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Clube da Troca / Praça Brasil', 'Belém', 'PA', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Jardins', 'Aracaju', 'SE', 'Quinta 14h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Praça Brasil / Umarizal', 'Belém', 'PA', 'Domingo 09h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Panini Point Fortaleza', 'Fortaleza', 'CE', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Floripa Shopping', 'Florianópolis', 'SC', 'Domingo 14h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Multi Open Shopping', 'Florianópolis', 'SC', 'Sábado 10h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Praça Popular', 'Cuiabá', 'MT', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Praça da Espanha', 'Curitiba', 'PR', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Park Shopping Boulevard', 'Curitiba', 'PR', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('ParkShoppingBarigüi', 'Curitiba', 'PR', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Jockey Plaza Shopping', 'Curitiba', 'PR', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Jardim das Américas', 'Curitiba', 'PR', '18h–20h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Estação', 'Curitiba', 'PR', '17h–20h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Curitiba', 'Curitiba', 'PR', 'Quinta 18h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Confraria das Figurinhas', 'Porto Alegre', 'RS', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Clube de Troca de Figurinhas', 'Porto Alegre', 'RS', 'Domingo 14h', 'Importado / pendente de validação', 'ponto_fixo', true),
('Panini Point / BarraShoppingSul', 'Porto Alegre', 'RS', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('BarraShoppingSul / Espaço de Trocas', 'Porto Alegre', 'RS', '17h–20h', 'Importado / pendente de validação', 'ponto_fixo', true),
('UFMG / Praça de Serviços', 'Belo Horizonte', 'MG', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Igrejinha da Pampulha', 'Belo Horizonte', 'MG', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Banca em frente ao EPA', 'Belo Horizonte', 'MG', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Banca do Rildo', 'Belo Horizonte', 'MG', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Banca do Carlão', 'Belo Horizonte', 'MG', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Banca em frente ao Colégio Arnaldo', 'Belo Horizonte', 'MG', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Banca da República do Líbano', 'Belo Horizonte', 'MG', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Coreto da Praça da Liberdade', 'Belo Horizonte', 'MG', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('DiamondMall', 'Belo Horizonte', 'MG', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Boulevard Shopping BH', 'Belo Horizonte', 'MG', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Pátio Savassi', 'Belo Horizonte', 'MG', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Praça da Ucrânia', 'Curitiba', 'PR', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Mueller', 'Curitiba', 'PR', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Shopping Cidade Curitiba', 'Curitiba', 'PR', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true),
('Pátio Batel', 'Curitiba', 'PR', 'Consultar', 'Importado / pendente de validação', 'ponto_fixo', true);
